[package]
name = "hypercounter"
description = "An atomic, lock-free, hash map-like counter structure."
version = "0.4.3"
edition = "2024"
license = "MIT"
authors = ["Nyeki"]
readme = "README.md"
repository = "https://github.com/Nekidev/hypercounter"

[dependencies]
papaya = "0.2.3"
